# Form implementation generated from reading ui file '.\ChangeFontWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

# Copyright (C) 2024 Yousef A. (Vyoxa).
# Licensed under the GPL-3.0 License.
# Created for KiraYume: https://github.com/Vyoxa/KiraYume

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Fonts(object):
    def setupUi(self, Fonts):
        Fonts.setObjectName("Fonts")
        Fonts.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Fonts)
        self.gridLayout.setObjectName("gridLayout")
        self.add_font_button = QtWidgets.QPushButton(parent=Fonts)
        self.add_font_button.setStyleSheet("QPushButton {\n"
"    color: #fcfcfc;\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #13a29a, stop:1 #1b95cb); \n"
"    padding: 8px;\n"
"    border-radius: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #146f97, stop:1 #0d6e69); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #0d4964, stop:1 #063b38); \n"
"}")
        self.add_font_button.setObjectName("add_font_button")
        self.gridLayout.addWidget(self.add_font_button, 1, 3, 1, 2)
        self.fonts_box = QtWidgets.QGroupBox(parent=Fonts)
        self.fonts_box.setStyleSheet("QGroupBox {\n"
"    color: #fcfcfc;\n"
"    border: 2px solid #13a29a;\n"
"    border-radius: 6px;\n"
"    margin-top: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 0 5px;\n"
"    color: #13a29a;\n"
"}\n"
"\n"
"QRadioButton {\n"
"    color: #E5E5E5;\n"
"    background-color: #333;\n"
"    padding: 3px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 7px;\n"
"    border: 2px solid #444;\n"
"    background: #222;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    border: 2px solid #009688;\n"
"    background: #003c45;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked:hover {\n"
"    border: 2px solid #666;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover {\n"
"    border: 2px solid #33a89f;\n"
"}\n"
"\n"
"QRadioButton:focus {\n"
"    outline: none;\n"
"}")
        self.fonts_box.setTitle("")
        self.fonts_box.setObjectName("fonts_box")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.fonts_box)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout.addWidget(self.fonts_box, 0, 0, 1, 5)
        self.open_folder_button = QtWidgets.QPushButton(parent=Fonts)
        self.open_folder_button.setStyleSheet("QPushButton {\n"
"    color: #fcfcfc;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #1b95cb, stop:1 #13a29a); \n"
"    padding: 8px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #0d6e69, stop:1 #146f97); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #063b38, stop:1 #0d4964); \n"
"}")
        self.open_folder_button.setObjectName("open_folder_button")
        self.gridLayout.addWidget(self.open_folder_button, 1, 2, 1, 1)
        self.reload_button = QtWidgets.QPushButton(parent=Fonts)
        self.reload_button.setStyleSheet("QPushButton {\n"
"    color: #fcfcfc;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #1b95cb, stop:1 #13a29a); \n"
"    padding: 8px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #0d6e69, stop:1 #146f97); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #063b38, stop:1 #0d4964); \n"
"}")
        self.reload_button.setObjectName("reload_button")
        self.gridLayout.addWidget(self.reload_button, 1, 0, 1, 2)

        self.retranslateUi(Fonts)
        QtCore.QMetaObject.connectSlotsByName(Fonts)

    def retranslateUi(self, Fonts):
        _translate = QtCore.QCoreApplication.translate
        Fonts.setWindowTitle(_translate("Fonts", "Form"))
        self.add_font_button.setText(_translate("Fonts", "Add new font"))
        self.open_folder_button.setText(_translate("Fonts", "Open fonts folder"))
        self.reload_button.setText(_translate("Fonts", "Reload"))
