# Form implementation generated from reading ui file '.\FormatNameWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

# Copyright (C) 2024 Yousef A. (Vyoxa).
# Licensed under the GPL-3.0 License.
# Created for KiraYume: https://github.com/Vyoxa/KiraYume


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(607, 314)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setStyleSheet("QFrame {\n"
"    border: 1px solid #148fa3;\n"
"    border-radius: 10px;\n"
"    border-width: 1px;\n"
"}\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setStyleSheet("QLabel {\n"
"    border: none\n"
"}")
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setStyleSheet("QLabel {\n"
"    border: none\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_6 = QtWidgets.QLabel(parent=self.frame)
        self.label_6.setStyleSheet("QLabel {\n"
"    border: none\n"
"}")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.gridLayout.addWidget(self.frame, 4, 0, 1, 3)
        self.frame_2 = QtWidgets.QFrame(parent=Form)
        self.frame_2.setStyleSheet("QFrame {\n"
"    border: none;\n"
"\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.save_button = QtWidgets.QPushButton(parent=self.frame_2)
        self.save_button.setEnabled(True)
        self.save_button.setStyleSheet("QPushButton {\n"
"    color: #d7d7d7;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.2 #148fa3, stop:1 #0d404e); \n"
"    border: none;\n"
"    padding: 8px 2px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border-radius: 10px;\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    color: #b7b7b7;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.2 #107282, stop:1 #0a333e); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #898989;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.2 #0d5b68, stop:1 #082932); \n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: #71adc1;\n"
"}\n"
"")
        self.save_button.setObjectName("save_button")
        self.gridLayout_2.addWidget(self.save_button, 2, 1, 1, 1)
        self.reset_button = QtWidgets.QPushButton(parent=self.frame_2)
        self.reset_button.setStyleSheet("QPushButton {\n"
"    color: #d7d7d7;\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0.420318, x2:0.955224, y2:0.966, stop:0.5 #101f32, stop:1 #148fa3);\n"
"    border: 1px solid rgba(0, 0, 0, 0);\n"
"    padding: 8px 2px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    border-radius: 14px;\n"
"    border-width: 2px;\n"
"}\n"
"\n"
"QPushButton:hover {    \n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0.420318, x2:0.955224, y2:0.966, stop:0.1 #101f32, stop:1 #148fa3);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #148fa3;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: #91abb9;\n"
"}\n"
"")
        self.reset_button.setObjectName("reset_button")
        self.gridLayout_2.addWidget(self.reset_button, 2, 0, 1, 1)
        self.name_format = QtWidgets.QLineEdit(parent=self.frame_2)
        self.name_format.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #101f32;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: #f5f5f5;\n"
"    color: #101f32;\n"
"    font: 14px \"Segoe UI\";\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #5a9bd4;\n"
"}\n"
"")
        self.name_format.setMaxLength(260)
        self.name_format.setFrame(False)
        self.name_format.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.name_format.setClearButtonEnabled(True)
        self.name_format.setObjectName("name_format")
        self.gridLayout_2.addWidget(self.name_format, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Variables: {original_name} {language_from} {language_to} {extension_suffix} {translator}"))
        self.label.setText(_translate("Form", "Name must end with either the original {extension_suffix} or a forced suffix (ex: .jpg  .png)"))
        self.label_6.setText(_translate("Form", "「EXAMPLE USAGE 」"))
        self.label_3.setText(_translate("Form", "Input: manga_001.png"))
        self.label_4.setText(_translate("Form", "Formatting: {translator}{original_name}_{language_from}_to_{language_to}.jpg"))
        self.label_5.setText(_translate("Form", "Output: Googlemanga_001_Japanese_to_English.jpg"))
        self.save_button.setText(_translate("Form", "Save"))
        self.reset_button.setText(_translate("Form", "Reset Default"))
        self.name_format.setText(_translate("Form", "{original_name}_{language_to){extension_suffix}"))
