# Form implementation generated from reading ui file '.\KiraYumeCreditsWidget.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

# Copyright (C) 2024 Yousef A. (Vyoxa).
# Licensed under the GPL-3.0 License.
# Created for KiraYume: https://github.com/Vyoxa/KiraYume

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setStyleSheet("QLabel {\n"
"    font-weight: bold; \n"
"}\n"
"")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(parent=Form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.KiraYumeGitHubPage = QtWidgets.QLabel(parent=self.frame_2)
        self.KiraYumeGitHubPage.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.KiraYumeGitHubPage.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.KiraYumeGitHubPage.setObjectName("KiraYumeGitHubPage")
        self.horizontalLayout.addWidget(self.KiraYumeGitHubPage)
        self.AppIcon = QtWidgets.QLabel(parent=self.frame_2)
        self.AppIcon.setMaximumSize(QtCore.QSize(128, 128))
        self.AppIcon.setText("")
        self.AppIcon.setPixmap(QtGui.QPixmap(".\\../../assets/AppIcon512.png"))
        self.AppIcon.setScaledContents(True)
        self.AppIcon.setObjectName("AppIcon")
        self.horizontalLayout.addWidget(self.AppIcon)
        self.ReleasesGitHubPage = QtWidgets.QLabel(parent=self.frame_2)
        self.ReleasesGitHubPage.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.ReleasesGitHubPage.setScaledContents(False)
        self.ReleasesGitHubPage.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ReleasesGitHubPage.setObjectName("ReleasesGitHubPage")
        self.horizontalLayout.addWidget(self.ReleasesGitHubPage)
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 4)
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.CreatorGitHubPage = QtWidgets.QLabel(parent=self.frame)
        self.CreatorGitHubPage.setStyleSheet("")
        self.CreatorGitHubPage.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.CreatorGitHubPage.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.CreatorGitHubPage.setObjectName("CreatorGitHubPage")
        self.gridLayout.addWidget(self.CreatorGitHubPage, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_4.setWordWrap(False)
        self.label_4.setOpenExternalLinks(False)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 1, 1, 1)
        self.ContributorsGitHubPage = QtWidgets.QLabel(parent=self.frame)
        self.ContributorsGitHubPage.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.ContributorsGitHubPage.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ContributorsGitHubPage.setObjectName("ContributorsGitHubPage")
        self.gridLayout.addWidget(self.ContributorsGitHubPage, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 3, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 1, 0, 1, 4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.KiraYumeGitHubPage.setText(_translate("Form", "<a href=\"https://github.com/Vyoxa/KiraYume\" style=\"text-decoration:none; color:#7289da; \">KiraYume</a>"))
        self.ReleasesGitHubPage.setText(_translate("Form", "<a href=\"https://github.com/Vyoxa/KiraYume/commits/main\" style=\"text-decoration:none; color:#7289da; \">Version 0.7</a>"))
        self.CreatorGitHubPage.setText(_translate("Form", "<a href=\"https://github.com/Vyoxa\" style=\"text-decoration:none; color:#7289da;\">Vyoxa</a>"))
        self.label_4.setText(_translate("Form", "Creator:"))
        self.label_2.setText(_translate("Form", "Discord ID:"))
        self.label.setText(_translate("Form", "vyoxa"))
        self.label_6.setText(_translate("Form", "Development:"))
        self.ContributorsGitHubPage.setText(_translate("Form", "<a href=\"https://github.com/Vyoxa/KiraYume/graphs/contributors\" style=\"text-decoration:none; color:#7289da;\">Contributors</a>"))
        self.label_3.setText(_translate("Form", "(Thank you ♥)"))
