# Form implementation generated from reading ui file '.\TesseractSettingsWidget.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

# Copyright (C) 2024 Yousef A. (Vyoxa).
# Licensed under the GPL-3.0 License.
# Created for KiraYume: https://github.com/Vyoxa/KiraYume

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(550, 296)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.close_button = QtWidgets.QPushButton(parent=self.frame)
        self.close_button.setStyleSheet("QPushButton {\n"
"    color: #fcfcfc;\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #13a29a, stop:1 #1b95cb); \n"
"    padding: 8px;\n"
"    border-radius: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #146f97, stop:1 #0d6e69); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #0d4964, stop:1 #063b38); \n"
"}")
        self.close_button.setObjectName("close_button")
        self.gridLayout_3.addWidget(self.close_button, 9, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(parent=self.frame)
        self.label_16.setStyleSheet("QLabel {\n"
"    font-weight: bold;\n"
"}")
        self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 0, 0, 1, 3)
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 3)
        self.download_here = QtWidgets.QLabel(parent=self.frame)
        self.download_here.setObjectName("download_here")
        self.gridLayout_3.addWidget(self.download_here, 3, 0, 1, 3)
        self.edit_exe_path_button = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_exe_path_button.sizePolicy().hasHeightForWidth())
        self.edit_exe_path_button.setSizePolicy(sizePolicy)
        self.edit_exe_path_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.edit_exe_path_button.setStyleSheet("QPushButton {\n"
"    color: #13a29a;\n"
"    font-weight: bold;\n"
"    background-color: none;\n"
"    border: none;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../assets/TesseractSettings512.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.edit_exe_path_button.setIcon(icon)
        self.edit_exe_path_button.setIconSize(QtCore.QSize(30, 35))
        self.edit_exe_path_button.setObjectName("edit_exe_path_button")
        self.gridLayout_3.addWidget(self.edit_exe_path_button, 2, 2, 1, 1)
        self.executable_path = QtWidgets.QLabel(parent=self.frame)
        self.executable_path.setStyleSheet("QLabel {\n"
"    border: 1px solid #13a29a;\n"
"    border-radius: 2px;\n"
"    border-width: 1px;\n"
"}")
        self.executable_path.setText("")
        self.executable_path.setObjectName("executable_path")
        self.gridLayout_3.addWidget(self.executable_path, 2, 0, 1, 2)
        self.open_tessdata_button = QtWidgets.QPushButton(parent=self.frame)
        self.open_tessdata_button.setStyleSheet("QPushButton {\n"
"    color: #fcfcfc;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #101f32, stop:0.7 #1b95cb); \n"
"    padding: 8px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #101f32, stop:0.9 #1b95cb); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #101f32, stop:1 #1b95cb); \n"
"}")
        self.open_tessdata_button.setObjectName("open_tessdata_button")
        self.gridLayout_3.addWidget(self.open_tessdata_button, 9, 0, 1, 1)
        self.traineddata_box = QtWidgets.QGroupBox(parent=self.frame)
        self.traineddata_box.setStyleSheet("QGroupBox {\n"
"    color: #fcfcfc;\n"
"    border: 2px solid #13a29a;\n"
"    border-radius: 6px;\n"
"    margin-top: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 0 5px;\n"
"    color: #13a29a;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QCheckBox {\n"
"    color: #fff;\n"
"    background-color: #333;\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 3px;\n"
"    border: 2px solid #444;\n"
"    background: #222;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    border: 2px solid #009688;\n"
"    background: #003c45;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    border: 2px solid #666;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    border: 2px solid #33a89f;\n"
"}\n"
"\n"
"QCheckBox:focus {\n"
"    outline: none;\n"
"}")
        self.traineddata_box.setTitle("")
        self.traineddata_box.setFlat(False)
        self.traineddata_box.setCheckable(False)
        self.traineddata_box.setObjectName("traineddata_box")
        self.gridLayout_3.addWidget(self.traineddata_box, 6, 0, 3, 3)
        self.reload_button = QtWidgets.QPushButton(parent=self.frame)
        self.reload_button.setStyleSheet("QPushButton {\n"
"    color: #fcfcfc;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #1b95cb, stop:1 #13a29a); \n"
"    padding: 8px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #0d6e69, stop:1 #146f97); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #063b38, stop:1 #0d4964); \n"
"}")
        self.reload_button.setObjectName("reload_button")
        self.gridLayout_3.addWidget(self.reload_button, 9, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 5, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.close_button.setText(_translate("Form", "Assign and Exit"))
        self.label_16.setText(_translate("Form", "「 TESSERACT OCR 」"))
        self.label.setText(_translate("Form", "Please select the location of tesseract.exe to enable OCR functionality."))
        self.download_here.setText(_translate("Form", " Don\'t have Tesseract OCR installed? you can download it from <a href=\"https://github.com/UB-Mannheim/tesseract/wiki\" style=\"text-decoration:none; color:#7289da;\">here.</a>"))
        self.edit_exe_path_button.setText(_translate("Form", "Choose Location"))
        self.open_tessdata_button.setText(_translate("Form", "Open tessdata folder"))
        self.reload_button.setText(_translate("Form", "Reload"))
